### ISSUE TITLE
[kong] proposed breaking changes for v2.0.0

### ISSUE THREAD

**Issue by rainest** [Kong/charts#73]
This issue collects proposed breaking changes for the next major release of the Kong Helm chart. It will be updated over time based on the status of the proposals.

If you are a chart user and believe a proposed change would be incompatible with your environment, please let us know in the comments.

Checked items are code complete and expected to arrive in the new version. Unchecked items are as of yet undecided, and may or may not have some WIP code available.

# Active/open proposals
- [ ] Remove support for Helm 2. Maintaining backwards compatibility introduces additional complexity (e.g. #33) and limits from using new Helm 3 features. Migrating is fairly simple, and Helm 3 can coexist with Helm 2 deployments, so we do not believe this should be a major concern in most environments.
- [x] Remove support for multiple proxy ingress hostnames (https://github.com/Kong/charts/blob/kong-1.3.1/charts/kong/values.yaml#L111-L127). This allows unifying the Ingress templates. We believe that this feature is primarily of use in environments where Kong is used alongside a non-Kong ingress controller, and the proxy is not a LoadBalancer service. We have not encountered many such configurations in practice.
- [x] Remove support for unique admin API listener configuration. Support for the standard configuration format was added in #72. This allows using a single Service template for Kong services.
- [x] Remove support for dedicated Portal session and authentication sections of values.yaml. #55  

# Rejected proposals
- [ ] Remove support for existing dedicated `http`/`tls` configuration blocks (https://github.com/Kong/charts/blob/kong-1.3.1/charts/kong/values.yaml#L111-L127) for services in favor of a generic listener configuration that supports stream listens as well. << stream listens are distinct enough that it doesn't really make sense to consolidate configuration of them. We've consolidated most of the underlying template logic to simplify development, but there's no compelling reason to change the UX here also.
